FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

COPY ./src ./

RUN ls -l /src

RUN dotnet publish -c Release -o /src/out

FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN dotnet tool install -g dotnet-ef --version 6.0.1

ENV PATH $PATH:/root/.dotnet/tools

WORKDIR /src

COPY --from=build /src .

WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8111
EXPOSE 8111

COPY --from=build /src/out .